-- MySQL Script generated by MySQL Workbench
-- Fri Jan 21 15:43:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET
@OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET
@OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET
@OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema swipe
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `swipe`;

-- -----------------------------------------------------
-- Schema swipe
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `swipe` DEFAULT CHARACTER SET utf8;
USE
`swipe` ;

-- -----------------------------------------------------
-- Table `swipe`.`residential_complexes_sales_departments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`residential_complexes_sales_departments`;

CREATE TABLE IF NOT EXISTS `swipe`.`residential_complexes_sales_departments`
(
    `id_residential_complex_sales_department`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `first_name`
    VARCHAR
(
    45
) NOT NULL,
    `second_name` VARCHAR
(
    45
) NOT NULL,
    `phone_number` VARCHAR
(
    45
) NOT NULL,
    `e_mail` VARCHAR
(
    255
) NOT NULL,
    PRIMARY KEY
(
    `id_residential_complex_sales_department`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`real_estate_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`real_estate_types`;

CREATE TABLE IF NOT EXISTS `swipe`.`real_estate_types`
(
    `id_real_estate_type`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `name`
    VARCHAR
(
    45
) NOT NULL,
    PRIMARY KEY
(
    `id_real_estate_type`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`residential_complexes_statuses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`residential_complexes_statuses`;

CREATE TABLE IF NOT EXISTS `swipe`.`residential_complexes_statuses`
(
    `id_residential_complex_status`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `name`
    VARCHAR
(
    45
) NOT NULL,
    PRIMARY KEY
(
    `id_residential_complex_status`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`residential_complexes_types_houses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`residential_complexes_types_houses`;

CREATE TABLE IF NOT EXISTS `swipe`.`residential_complexes_types_houses`
(
    `id_residential_complex_type_house`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `name`
    VARCHAR
(
    45
) NOT NULL,
    PRIMARY KEY
(
    `id_residential_complex_type_house`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`residential_complexes_classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`residential_complexes_classes`;

CREATE TABLE IF NOT EXISTS `swipe`.`residential_complexes_classes`
(
    `id_residential_complex_classes`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `name`
    VARCHAR
(
    45
) NOT NULL,
    PRIMARY KEY
(
    `id_residential_complex_classes`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`residential_complexes_construction_technologies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`residential_complexes_construction_technologies`;

CREATE TABLE IF NOT EXISTS `swipe`.`residential_complexes_construction_technologies`
(
    `id_residential_complex_construction_technology`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `name`
    VARCHAR
(
    45
) NOT NULL,
    PRIMARY KEY
(
    `id_residential_complex_construction_technology`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`residential_complexes_area_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`residential_complexes_area_types`;

CREATE TABLE IF NOT EXISTS `swipe`.`residential_complexes_area_types`
(
    `id_residential_complex_area_type`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `name`
    VARCHAR
(
    45
) NOT NULL,
    PRIMARY KEY
(
    `id_residential_complex_area_type`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`residential_complexes_communal_payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`residential_complexes_communal_payments`;

CREATE TABLE IF NOT EXISTS `swipe`.`residential_complexes_communal_payments`
(
    `id_residential_complex_communal_payment`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `name`
    VARCHAR
(
    45
) NOT NULL,
    PRIMARY KEY
(
    `id_residential_complex_communal_payment`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`residential_complexes_gas_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`residential_complexes_gas_types`;

CREATE TABLE IF NOT EXISTS `swipe`.`residential_complexes_gas_types`
(
    `id_residential_complex_gas_type`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `name`
    VARCHAR
(
    45
) NOT NULL,
    PRIMARY KEY
(
    `id_residential_complex_gas_type`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`residential_complexes_heating_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`residential_complexes_heating_types`;

CREATE TABLE IF NOT EXISTS `swipe`.`residential_complexes_heating_types`
(
    `id_residential_complex_heating_type`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `name`
    VARCHAR
(
    45
) NOT NULL,
    PRIMARY KEY
(
    `id_residential_complex_heating_type`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`residential_complexes_sewerage_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`residential_complexes_sewerage_types`;

CREATE TABLE IF NOT EXISTS `swipe`.`residential_complexes_sewerage_types`
(
    `id_residential_complex_sewerage_type`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `name`
    VARCHAR
(
    45
) NOT NULL,
    PRIMARY KEY
(
    `id_residential_complex_sewerage_type`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`residential_complexes_water_supply_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`residential_complexes_water_supply_types`;

CREATE TABLE IF NOT EXISTS `swipe`.`residential_complexes_water_supply_types`
(
    `id_residential_complex_water_supply_type`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `name`
    VARCHAR
(
    45
) NOT NULL,
    PRIMARY KEY
(
    `id_residential_complex_water_supply_type`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`residential_complexes_descriptions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`residential_complexes_descriptions`;

CREATE TABLE IF NOT EXISTS `swipe`.`residential_complexes_descriptions`
(
    `id_residential_complex_description`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `id_residential_complex_status`
    INT
    NOT
    NULL,
    `id_residential_complex_type_house`
    INT
    NOT
    NULL,
    `id_residential_complex_classes`
    INT
    NOT
    NULL,
    `id_residential_complex_construction_technology`
    INT
    NOT
    NULL,
    `id_residential_complex_area_type`
    INT
    NOT
    NULL,
    `id_residential_complex_communal_payment`
    INT
    NOT
    NULL,
    `id_residential_complex_gas_type`
    INT
    NOT
    NULL,
    `id_residential_complex_heating_type`
    INT
    NOT
    NULL,
    `id_residential_complex_sewerage_type`
    INT
    NOT
    NULL,
    `id_residential_complex_water_supply_type`
    INT
    NOT
    NULL,
    `distance_to_sea`
    INT
    NOT
    NULL,
    `ceiling_height`
    INT
    NOT
    NULL,
    PRIMARY
    KEY
(
    `id_residential_complex_description`
),
    INDEX `fk_descriptions_residential_complexes_idx`
(
    `id_residential_complex_status` ASC
) VISIBLE,
    INDEX `fk_descriptions_residential_complexes_idx1`
(
    `id_residential_complex_type_house` ASC
) VISIBLE,
    INDEX `fk_descriptions_residential_complexes_idx2`
(
    `id_residential_complex_classes` ASC
) VISIBLE,
    INDEX `fk_descriptions_residential_complexes_idx3`
(
    `id_residential_complex_construction_technology` ASC
) VISIBLE,
    INDEX `fk_descriptions_residential_complexes_idx4`
(
    `id_residential_complex_area_type` ASC
) VISIBLE,
    INDEX `fk_descriptions_residential_complexes_idx5`
(
    `id_residential_complex_communal_payment` ASC
) VISIBLE,
    INDEX `fk_descriptions_residential_complexes_idx6`
(
    `id_residential_complex_gas_type` ASC
) VISIBLE,
    INDEX `fk_descriptions_residential_complexes_idx7`
(
    `id_residential_complex_heating_type` ASC
) VISIBLE,
    INDEX `fk_descriptions_residential_complexes_idx8`
(
    `id_residential_complex_sewerage_type` ASC
) VISIBLE,
    INDEX `fk_descriptions_residential_complexes_idx9`
(
    `id_residential_complex_water_supply_type` ASC
) VISIBLE,
    CONSTRAINT `fk_descriptions_statuses`
    FOREIGN KEY
(
    `id_residential_complex_status`
)
    REFERENCES `swipe`.`residential_complexes_statuses`
(
    `id_residential_complex_status`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_descriptions_types_houses`
    FOREIGN KEY
(
    `id_residential_complex_type_house`
)
    REFERENCES `swipe`.`residential_complexes_types_houses`
(
    `id_residential_complex_type_house`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_descriptions_classes`
    FOREIGN KEY
(
    `id_residential_complex_classes`
)
    REFERENCES `swipe`.`residential_complexes_classes`
(
    `id_residential_complex_classes`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_descriptions_construction_technologies`
    FOREIGN KEY
(
    `id_residential_complex_construction_technology`
)
    REFERENCES `swipe`.`residential_complexes_construction_technologies`
(
    `id_residential_complex_construction_technology`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_descriptions_area_types`
    FOREIGN KEY
(
    `id_residential_complex_area_type`
)
    REFERENCES `swipe`.`residential_complexes_area_types`
(
    `id_residential_complex_area_type`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_descriptions_communal_payments`
    FOREIGN KEY
(
    `id_residential_complex_communal_payment`
)
    REFERENCES `swipe`.`residential_complexes_communal_payments`
(
    `id_residential_complex_communal_payment`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_descriptions_gas_types`
    FOREIGN KEY
(
    `id_residential_complex_gas_type`
)
    REFERENCES `swipe`.`residential_complexes_gas_types`
(
    `id_residential_complex_gas_type`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_descriptions_heating_types`
    FOREIGN KEY
(
    `id_residential_complex_heating_type`
)
    REFERENCES `swipe`.`residential_complexes_heating_types`
(
    `id_residential_complex_heating_type`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_descriptions_sewerage_types`
    FOREIGN KEY
(
    `id_residential_complex_sewerage_type`
)
    REFERENCES `swipe`.`residential_complexes_sewerage_types`
(
    `id_residential_complex_sewerage_type`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_descriptions_water_supply_types`
    FOREIGN KEY
(
    `id_residential_complex_water_supply_type`
)
    REFERENCES `swipe`.`residential_complexes_water_supply_types`
(
    `id_residential_complex_water_supply_type`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`account_types`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`account_types`;

CREATE TABLE IF NOT EXISTS `swipe`.`account_types`
(
    `id_account_type`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `name`
    VARCHAR
(
    45
) NOT NULL,
    PRIMARY KEY
(
    `id_account_type`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`account_type_developers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`account_type_developers`;

CREATE TABLE IF NOT EXISTS `swipe`.`account_type_developers`
(
    `id_account_type_developer`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `id_account_type`
    INT
    NOT
    NULL,
    PRIMARY
    KEY
(
    `id_account_type_developer`
),
    INDEX `personal_account_developers_accounts_types_idx`
(
    `id_account_type` ASC
) VISIBLE,
    CONSTRAINT `fk_account_type_developers_accounts_types`
    FOREIGN KEY
(
    `id_account_type`
)
    REFERENCES `swipe`.`account_types`
(
    `id_account_type`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`residential_complexes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`residential_complexes`;

CREATE TABLE IF NOT EXISTS `swipe`.`residential_complexes`
(
    `id_residential_complex`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `id_real_estate_type`
    INT
    NOT
    NULL,
    `id_account_type_developer`
    INT
    NOT
    NULL,
    `id_residential_complex_sales_department`
    INT
    NOT
    NULL,
    `id_residential_complex_description`
    INT
    NOT
    NULL,
    `name`
    VARCHAR
(
    45
) NOT NULL,
    `address` VARCHAR
(
    45
) NOT NULL,
    `coordinates_for_map` VARCHAR
(
    255
) NOT NULL,
    PRIMARY KEY
(
    `id_residential_complex`
),
    INDEX `fk_residential_complexes_sales_depart_idx`
(
    `id_residential_complex_sales_department` ASC
) INVISIBLE,
    INDEX `fk_residential_complexes_real_estates_types_idx`
(
    `id_real_estate_type` ASC
) VISIBLE,
    INDEX `fk_residential_complexes_residential_complexes_descriptions_idx`
(
    `id_residential_complex_description` ASC
) VISIBLE,
    INDEX `fk_residential_complexes_personal_account_developers_idx`
(
    `id_account_type_developer` ASC
) VISIBLE,
    CONSTRAINT `fk_residential_complexes_sales_departments`
    FOREIGN KEY
(
    `id_residential_complex_sales_department`
)
    REFERENCES `swipe`.`residential_complexes_sales_departments`
(
    `id_residential_complex_sales_department`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_residential_complexes_real_estate_types`
    FOREIGN KEY
(
    `id_real_estate_type`
)
    REFERENCES `swipe`.`real_estate_types`
(
    `id_real_estate_type`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_residential_complexes_residential_complexes_descriptions`
    FOREIGN KEY
(
    `id_residential_complex_description`
)
    REFERENCES `swipe`.`residential_complexes_descriptions`
(
    `id_residential_complex_description`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_residential_complexes_account_type_developers`
    FOREIGN KEY
(
    `id_account_type_developer`
)
    REFERENCES `swipe`.`account_type_developers`
(
    `id_account_type_developer`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`authorizations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`authorizations`;

CREATE TABLE IF NOT EXISTS `swipe`.`authorizations`
(
    `id_authorization`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `login`
    VARCHAR
(
    100
) NOT NULL,
    `password` VARCHAR
(
    100
) NOT NULL,
    `enabled` BIT NOT NULL,
    `jwt_refresh` MEDIUMTEXT NULL,
    `jwt_refresh_secret` MEDIUMTEXT NULL,
    PRIMARY KEY
(
    `id_authorization`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`agents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`agents`;

CREATE TABLE IF NOT EXISTS `swipe`.`agents`
(
    `id_agent`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `first_name`
    VARCHAR
(
    45
) NOT NULL,
    `second_name` VARCHAR
(
    45
) NOT NULL,
    `phone_number` VARCHAR
(
    45
) NOT NULL,
    `e_mail` VARCHAR
(
    255
) NOT NULL,
    PRIMARY KEY
(
    `id_agent`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`account_type_private_persons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`account_type_private_persons`;

CREATE TABLE IF NOT EXISTS `swipe`.`account_type_private_persons`
(
    `id_account_type_private_person`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `id_account_type`
    INT
    NOT
    NULL,
    `id_agent`
    INT
    NULL,
    `forwarding_to_agent`
    BIT
    NOT
    NULL,
    PRIMARY
    KEY
(
    `id_account_type_private_person`
),
    INDEX `fk_personal_accounts_private_person_agents_idx`
(
    `id_agent` ASC
) VISIBLE,
    INDEX `fk_personal_account_private_persons_account_types_idx`
(
    `id_account_type` ASC
) VISIBLE,
    CONSTRAINT `fk_account_type_private_persons_agents`
    FOREIGN KEY
(
    `id_agent`
)
    REFERENCES `swipe`.`agents`
(
    `id_agent`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_account_type_private_persons_account_types`
    FOREIGN KEY
(
    `id_account_type`
)
    REFERENCES `swipe`.`account_types`
(
    `id_account_type`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`account_type_admins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`account_type_admins`;

CREATE TABLE IF NOT EXISTS `swipe`.`account_type_admins`
(
    `id_account_type_admin`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `id_account_type`
    INT
    NOT
    NULL,
    PRIMARY
    KEY
(
    `id_account_type_admin`
),
    INDEX `fk_personal_account_admins_account_types_idx`
(
    `id_account_type` ASC
) VISIBLE,
    CONSTRAINT `fk_personal_account_admins_account_types`
    FOREIGN KEY
(
    `id_account_type`
)
    REFERENCES `swipe`.`account_types`
(
    `id_account_type`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`personal_accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`personal_accounts`;

CREATE TABLE IF NOT EXISTS `swipe`.`personal_accounts`
(
    `id_personal_account`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `id_account_type`
    INT
    NOT
    NULL,
    `id_authorization`
    INT
    NOT
    NULL,
    `first_name`
    VARCHAR
(
    45
) NOT NULL,
    `second_name` VARCHAR
(
    45
) NOT NULL,
    `path_to_image` VARCHAR
(
    255
) NULL,
    PRIMARY KEY
(
    `id_personal_account`
),
    INDEX `fk_personal_accounts_authorizations_idx`
(
    `id_authorization` ASC
) VISIBLE,
    INDEX `fk_personal_accounts_account_types_idx`
(
    `id_account_type` ASC
) VISIBLE,
    CONSTRAINT `fk_personal_accounts_authorizations`
    FOREIGN KEY
(
    `id_authorization`
)
    REFERENCES `swipe`.`authorizations`
(
    `id_authorization`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_personal_accounts_account_types`
    FOREIGN KEY
(
    `id_account_type`
)
    REFERENCES `swipe`.`account_types`
(
    `id_account_type`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`residential_complexes_galleries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`residential_complexes_galleries`;

CREATE TABLE IF NOT EXISTS `swipe`.`residential_complexes_galleries`
(
    `id_residential_complex_gallery`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `id_residential_complex`
    INT
    NOT
    NULL,
    `path_to_image`
    VARCHAR
(
    255
) NOT NULL,
    PRIMARY KEY
(
    `id_residential_complex_gallery`
),
    INDEX `fk_residential_complexes_galleries_residential_complexes_idx`
(
    `id_residential_complex` ASC
) VISIBLE,
    CONSTRAINT `fk_residential_complexes_galleries_residential_complexes`
    FOREIGN KEY
(
    `id_residential_complex`
)
    REFERENCES `swipe`.`residential_complexes`
(
    `id_residential_complex`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`apartments_buildings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`apartments_buildings`;

CREATE TABLE IF NOT EXISTS `swipe`.`apartments_buildings`
(
    `id_apartment_building`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `number_building`
    INT
    NOT
    NULL,
    PRIMARY
    KEY
(
    `id_apartment_building`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`residential_complexes_news`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`residential_complexes_news`;

CREATE TABLE IF NOT EXISTS `swipe`.`residential_complexes_news`
(
    `id_residential_complex_news`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `id_residential_complex`
    INT
    NOT
    NULL,
    `name`
    VARCHAR
(
    45
) NOT NULL,
    `description` MEDIUMTEXT NOT NULL,
    `creation_date` DATE NOT NULL,
    PRIMARY KEY
(
    `id_residential_complex_news`
),
    INDEX `residential_complexes_news_residential_complexes_idx`
(
    `id_residential_complex` ASC
) VISIBLE,
    CONSTRAINT `residential_complexes_news_residential_complexes`
    FOREIGN KEY
(
    `id_residential_complex`
)
    REFERENCES `swipe`.`residential_complexes`
(
    `id_residential_complex`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`residential_complexes_files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`residential_complexes_files`;

CREATE TABLE IF NOT EXISTS `swipe`.`residential_complexes_files`
(
    `id_residential_complex_file`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `id_residential_complex`
    INT
    NOT
    NULL,
    `path_to_file`
    VARCHAR
(
    255
) NOT NULL,
    PRIMARY KEY
(
    `id_residential_complex_file`
),
    INDEX `residential_complexes_files_residential_complexes_idx`
(
    `id_residential_complex` ASC
) VISIBLE,
    CONSTRAINT `residential_complexes_files_residential_complexes`
    FOREIGN KEY
(
    `id_residential_complex`
)
    REFERENCES `swipe`.`residential_complexes`
(
    `id_residential_complex`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`apartments_description_foundation_documents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`apartments_description_foundation_documents`;

CREATE TABLE IF NOT EXISTS `swipe`.`apartments_description_foundation_documents`
(
    `id_apartment_description_foundation_document`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `name`
    VARCHAR
(
    45
) NOT NULL,
    PRIMARY KEY
(
    `id_apartment_description_foundation_document`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`apartments_description_appointments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`apartments_description_appointments`;

CREATE TABLE IF NOT EXISTS `swipe`.`apartments_description_appointments`
(
    `id_apartment_description_appointment`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `name`
    VARCHAR
(
    45
) NOT NULL,
    PRIMARY KEY
(
    `id_apartment_description_appointment`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`apartments_description_number_of_rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`apartments_description_number_of_rooms`;

CREATE TABLE IF NOT EXISTS `swipe`.`apartments_description_number_of_rooms`
(
    `id_apartment_description_number_of_room`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `name`
    VARCHAR
(
    45
) NOT NULL,
    PRIMARY KEY
(
    `id_apartment_description_number_of_room`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`apartments_description_layouts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`apartments_description_layouts`;

CREATE TABLE IF NOT EXISTS `swipe`.`apartments_description_layouts`
(
    `id_apartment_description_layout`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `name`
    VARCHAR
(
    45
) NOT NULL,
    PRIMARY KEY
(
    `id_apartment_description_layout`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`apartments_description_living_conditions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`apartments_description_living_conditions`;

CREATE TABLE IF NOT EXISTS `swipe`.`apartments_description_living_conditions`
(
    `id_apartment_description_living_condition`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `name`
    VARCHAR
(
    45
) NOT NULL,
    PRIMARY KEY
(
    `id_apartment_description_living_condition`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`apartments_description_balconies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`apartments_description_balconies`;

CREATE TABLE IF NOT EXISTS `swipe`.`apartments_description_balconies`
(
    `id_apartment_description_balcony`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `name`
    VARCHAR
(
    45
) NOT NULL,
    PRIMARY KEY
(
    `id_apartment_description_balcony`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`apartments_description_calculation_options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`apartments_description_calculation_options`;

CREATE TABLE IF NOT EXISTS `swipe`.`apartments_description_calculation_options`
(
    `id_apartment_description_calculation_option`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `name`
    VARCHAR
(
    45
) NOT NULL,
    PRIMARY KEY
(
    `id_apartment_description_calculation_option`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`apartments_description_agent_commissions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`apartments_description_agent_commissions`;

CREATE TABLE IF NOT EXISTS `swipe`.`apartments_description_agent_commissions`
(
    `id_apartment_description_agent_commission`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `name`
    VARCHAR
(
    45
) NOT NULL,
    PRIMARY KEY
(
    `id_apartment_description_agent_commission`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`apartments_description_ways_of_communication`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`apartments_description_ways_of_communication`;

CREATE TABLE IF NOT EXISTS `swipe`.`apartments_description_ways_of_communication`
(
    `id_apartment_description_way_of_communication`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `name`
    VARCHAR
(
    45
) NOT NULL,
    PRIMARY KEY
(
    `id_apartment_description_way_of_communication`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`apartments_description`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`apartments_description`;

CREATE TABLE IF NOT EXISTS `swipe`.`apartments_description`
(
    `id_apartment_description`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `id_apartment_description_foundation_document`
    INT
    NOT
    NULL,
    `id_apartment_description_appointment`
    INT
    NOT
    NULL,
    `id_apartment_description_number_of_room`
    INT
    NOT
    NULL,
    `id_apartment_description_calculation_option`
    INT
    NOT
    NULL,
    `id_apartment_description_layout`
    INT
    NOT
    NULL,
    `id_apartment_description_living_condition`
    INT
    NOT
    NULL,
    `id_apartment_description_balcony`
    INT
    NOT
    NULL,
    `id_apartment_description_agent_commission`
    INT
    NOT
    NULL,
    `id_apartment_description_way_of_communication`
    INT
    NOT
    NULL,
    PRIMARY
    KEY
(
    `id_apartment_description`
),
    INDEX `fk_appartments_description_private_persons_foundation_docum_idx`
(
    `id_apartment_description_foundation_document` ASC
) VISIBLE,
    INDEX `fk_appartments_description_private_persons_appointments_idx`
(
    `id_apartment_description_appointment` ASC
) VISIBLE,
    INDEX `fk_appartments_description_private_persons_number_of_rooms_idx`
(
    `id_apartment_description_number_of_room` ASC
) VISIBLE,
    INDEX `fk_appartments_description_private_persons_calculation_opti_idx`
(
    `id_apartment_description_calculation_option` ASC
) VISIBLE,
    INDEX `fk_appartments_description_private_persons_layouts_idx`
(
    `id_apartment_description_layout` ASC
) VISIBLE,
    INDEX `fk_appartments_description_private_persons_living_condition_idx`
(
    `id_apartment_description_living_condition` ASC
) VISIBLE,
    INDEX `fk_appartments_description_private_persons_balconies_idx`
(
    `id_apartment_description_balcony` ASC
) VISIBLE,
    INDEX `fk_appartments_description_private_persons_agent_commission_idx`
(
    `id_apartment_description_agent_commission` ASC
) VISIBLE,
    INDEX `fk_appartments_description_private_persons_ways_of_communic_idx`
(
    `id_apartment_description_way_of_communication` ASC
) VISIBLE,
    CONSTRAINT `fk_appartments_description_private_persons_foundation_documents`
    FOREIGN KEY
(
    `id_apartment_description_foundation_document`
)
    REFERENCES `swipe`.`apartments_description_foundation_documents`
(
    `id_apartment_description_foundation_document`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_appartments_description_private_persons_appointments`
    FOREIGN KEY
(
    `id_apartment_description_appointment`
)
    REFERENCES `swipe`.`apartments_description_appointments`
(
    `id_apartment_description_appointment`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_appartments_description_private_persons_number_of_rooms`
    FOREIGN KEY
(
    `id_apartment_description_number_of_room`
)
    REFERENCES `swipe`.`apartments_description_number_of_rooms`
(
    `id_apartment_description_number_of_room`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_appartments_description_private_persons_calculation_options`
    FOREIGN KEY
(
    `id_apartment_description_calculation_option`
)
    REFERENCES `swipe`.`apartments_description_calculation_options`
(
    `id_apartment_description_calculation_option`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_appartments_description_private_persons_layouts`
    FOREIGN KEY
(
    `id_apartment_description_layout`
)
    REFERENCES `swipe`.`apartments_description_layouts`
(
    `id_apartment_description_layout`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_appartments_description_private_persons_living_conditions`
    FOREIGN KEY
(
    `id_apartment_description_living_condition`
)
    REFERENCES `swipe`.`apartments_description_living_conditions`
(
    `id_apartment_description_living_condition`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_appartments_description_private_persons_balconies`
    FOREIGN KEY
(
    `id_apartment_description_balcony`
)
    REFERENCES `swipe`.`apartments_description_balconies`
(
    `id_apartment_description_balcony`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_appartments_description_private_persons_agent_commissions`
    FOREIGN KEY
(
    `id_apartment_description_agent_commission`
)
    REFERENCES `swipe`.`apartments_description_agent_commissions`
(
    `id_apartment_description_agent_commission`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_appartments_description_private_persons_ways_of_communication`
    FOREIGN KEY
(
    `id_apartment_description_way_of_communication`
)
    REFERENCES `swipe`.`apartments_description_ways_of_communication`
(
    `id_apartment_description_way_of_communication`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`apartments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`apartments`;

CREATE TABLE IF NOT EXISTS `swipe`.`apartments`
(
    `id_apartment`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `id_real_estate_type`
    INT
    NOT
    NULL,
    `id_account_type_private_person`
    INT
    NULL,
    `id_apartment_description`
    INT
    NOT
    NULL,
    `id_residential_complex`
    INT
    NOT
    NULL,
    `id_apartment_building`
    INT
    NOT
    NULL,
    `price`
    DOUBLE
    NOT
    NULL,
    `size`
    DOUBLE
    NOT
    NULL,
    PRIMARY
    KEY
(
    `id_apartment`
),
    INDEX `fk_appartments_residential_complexes_idx`
(
    `id_residential_complex` ASC
) VISIBLE,
    INDEX `fk_appartments_residential_complexes_buildings_idx`
(
    `id_apartment_building` ASC
) VISIBLE,
    INDEX `fk_appartments_real_estates_types_idx`
(
    `id_real_estate_type` ASC
) VISIBLE,
    INDEX `fk_appartments_appartments_description_idx`
(
    `id_apartment_description` ASC
) VISIBLE,
    INDEX `fk_apartments_personal_account_private_persons_idx`
(
    `id_account_type_private_person` ASC
) VISIBLE,
    CONSTRAINT `fk_appartments_residential_complexes`
    FOREIGN KEY
(
    `id_residential_complex`
)
    REFERENCES `swipe`.`residential_complexes`
(
    `id_residential_complex`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_appartments_residential_complexes_buildings`
    FOREIGN KEY
(
    `id_apartment_building`
)
    REFERENCES `swipe`.`apartments_buildings`
(
    `id_apartment_building`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_appartments_real_estate_types`
    FOREIGN KEY
(
    `id_real_estate_type`
)
    REFERENCES `swipe`.`real_estate_types`
(
    `id_real_estate_type`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_appartments_appartments_description`
    FOREIGN KEY
(
    `id_apartment_description`
)
    REFERENCES `swipe`.`apartments_description`
(
    `id_apartment_description`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT `fk_apartments_personal_account_type_private_persons`
    FOREIGN KEY
(
    `id_account_type_private_person`
)
    REFERENCES `swipe`.`account_type_private_persons`
(
    `id_account_type_private_person`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`apartments_galleries`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`apartments_galleries`;

CREATE TABLE IF NOT EXISTS `swipe`.`apartments_galleries`
(
    `id_apartment_gallery`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `id_apartment`
    INT
    NOT
    NULL,
    `path_to_image`
    VARCHAR
(
    255
) NOT NULL,
    PRIMARY KEY
(
    `id_apartment_gallery`
),
    INDEX `fk_apartments_galleries_apartments_idx`
(
    `id_apartment` ASC
) VISIBLE,
    CONSTRAINT `fk_apartments_galleries_apartments`
    FOREIGN KEY
(
    `id_apartment`
)
    REFERENCES `swipe`.`apartments`
(
    `id_apartment`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`residential_complex_ads`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`residential_complex_ads`;

CREATE TABLE IF NOT EXISTS `swipe`.`residential_complex_ads`
(
    `id_ad`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `id_residential_complex`
    INT
    NOT
    NULL,
    `enabled`
    BIT
    NOT
    NULL
    DEFAULT
    1,
    PRIMARY
    KEY
(
    `id_ad`
),
    INDEX `fk_residential_complex_ads_residential_complexes_idx`
(
    `id_residential_complex` ASC
) VISIBLE,
    CONSTRAINT `fk_residential_complex_ads_residential_complexes`
    FOREIGN KEY
(
    `id_residential_complex`
)
    REFERENCES `swipe`.`residential_complexes`
(
    `id_residential_complex`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`jwt_secrets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`jwt_secrets`;

CREATE TABLE IF NOT EXISTS `swipe`.`jwt_secrets`
(
    `id_jwt_secret`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `jwt_secret`
    MEDIUMTEXT
    NOT
    NULL,
    PRIMARY
    KEY
(
    `id_jwt_secret`
))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `swipe`.`apartment_ads`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `swipe`.`apartment_ads`;

CREATE TABLE IF NOT EXISTS `swipe`.`apartment_ads`
(
    `id_apartment_ad`
    INT
    NOT
    NULL
    AUTO_INCREMENT,
    `id_apartment`
    INT
    NOT
    NULL,
    `enabled`
    BIT
    NOT
    NULL
    DEFAULT
    1,
    PRIMARY
    KEY
(
    `id_apartment_ad`
),
    INDEX `apartment_ads_apartments_idx`
(
    `id_apartment` ASC
) VISIBLE,
    CONSTRAINT `apartment_ads_apartments`
    FOREIGN KEY
(
    `id_apartment`
)
    REFERENCES `swipe`.`apartments`
(
    `id_apartment`
)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
    ENGINE = InnoDB;


SET
SQL_MODE=@OLD_SQL_MODE;
SET
FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET
UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
